=== kheirus/gedcom_to_xml/gedcom.dtd
<!-- 
*******************************************************
***** This DTD validates GEDCOM v 5.5.1 	   ********
***** Copyright 2014 K. Ouelaa & R. Oubraim  ********
******************************************************
-->


	<!-- GEDCOM : root -->
<!ELEMENT gedcom (head? | subm? | indi+ | fam | trlr?)*>

	<!-- HEAD -->
<!ELEMENT head (sour? | dest? | date?| char? | file? | gedc?)*>

<!ELEMENT sour (#PCDATA | vers | name | corp)* >
<!ATTLIST sour id ID #IMPLIED>
  
<!ELEMENT vers (#PCDATA)>
<!ELEMENT corp (#PCDATA | addr | phon)* >
<!ELEMENT dest (#PCDATA)>
<!ELEMENT char (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT gedc (vers)?>


	<!-- 0 SUBM -->
<!ELEMENT subm (sname | addr | phon | comm)*>
<!ELEMENT sname (#PCDATA)>
<!ATTLIST subm id ID #REQUIRED>

<!ELEMENT addr (#PCDATA | cont)*>
<!ELEMENT phon (#PCDATA)>
<!ELEMENT comm (#PCDATA | cont)*>
<!ELEMENT cont (#PCDATA)>

	<!-- 0 INDI -->
<!ELEMENT indi (name? | titl? | sex? | sour? | chan? | birt? | deat? | buri? | refn? | chr? | famc? | fams | obje?)*>
<!ATTLIST indi id ID #REQUIRED>

<!ELEMENT name (firstname?,lastname?)*>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!ELEMENT titl (#PCDATA)>
<!ELEMENT sex EMPTY>
<!ATTLIST sex type (M|F) #REQUIRED>
<!-- sour deja defini-->
<!ELEMENT chan EMPTY>
<!ELEMENT birt (date?| plac?)*>
    <!-- DATE -->
<!ELEMENT date (d?,m?,y?)>
<!ELEMENT d (#PCDATA)>
<!ELEMENT m (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ATTLIST date spec CDATA #IMPLIED>
	<!-- PLAC -->
<!ELEMENT plac (#PCDATA)>

<!ELEMENT deat (date? | plac?)*>
<!ELEMENT buri (date? | plac?)*>
<!ELEMENT refn (#PCDATA)>
<!ELEMENT chr (date? | plac?)*>

<!ELEMENT famc EMPTY>
<!ATTLIST famc ref IDREF #REQUIRED>

<!ELEMENT fams EMPTY>	
<!ATTLIST fams ref IDREF #REQUIRED>


	<!-- 0 FAM  -->
<!ELEMENT fam (husb? | wife? | chil | div? | marr? | obje?)*>
<!ATTLIST fam id ID #REQUIRED>

<!ELEMENT husb EMPTY>
<!ATTLIST husb ref IDREF #REQUIRED>

<!ELEMENT wife EMPTY>
<!ATTLIST wife ref IDREF #REQUIRED>

<!ELEMENT chil EMPTY>
<!ATTLIST chil ref IDREF #REQUIRED>

<!ELEMENT div EMPTY>
<!ATTLIST div isdiv (Y|N) #IMPLIED>

<!ELEMENT marr (date? | plac?)*>

<!ELEMENT obje (file?| form?| titl?)*>

<!ELEMENT form (#PCDATA)>


	<!-- 0 TRLR -->
<!ELEMENT trlr EMPTY>

=== kheirus/gedcom_to_xml/xml_generated_files/begood.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gedcom SYSTEM "gedcom.dtd">
<gedcom>
  <head>
    <sour>UNSPECIFIED</sour>
    <char>ANSEL</char>
  </head>
  <indi id="I1">
    <name>
      <firstname>John</firstname>
      <lastname>Begood</lastname>
    </name>
    <sex type="M" />
    <fams ref="F1" />
  </indi>
  <indi id="I2">
    <name>
      <firstname>Ada</firstname>
      <lastname>Begood</lastname>
    </name>
    <fams ref="F1" />
  </indi>
  <indi id="I3">
    <name>
      <lastname>Begood</lastname>
    </name>
    <famc ref="F1" />
  </indi>
  <indi id="I4">
    <name>
      <firstname>Lea</firstname>
      <lastname>Begood</lastname>
    </name>
    <sex type="F" />
    <famc ref="F1" />
  </indi>
  <fam id="F1">
    <husb ref="I1" />
    <wife ref="I2" />
    <chil ref="I3" />
    <chil ref="I4" />
  </fam>
  <trlr />
</gedcom>

=== kheirus/gedcom_to_xml/xml_generated_files/complet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gedcom SYSTEM "gedcom.dtd">
<gedcom>
  <head>
    <sour>UNSPECIFIED</sour>
    <char>ANSEL</char>
  </head>
  <indi id="I10">
    <name>
      <firstname>Nicole</firstname>
      <lastname>von Neumann</lastname>
    </name>
    <sex type="F" />
    <fams ref="F5" />
  </indi>
  <indi id="I15">
    <name>
      <firstname>David</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <famc ref="F4" />
  </indi>
  <indi id="I9">
    <name>
      <firstname>Manuel</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <fams ref="F5" />
    <famc ref="F2" />
  </indi>
  <indi id="I12">
    <name>
      <firstname>S?verine</firstname>
      <lastname>B?chi</lastname>
    </name>
    <sex type="F" />
    <famc ref="F3" />
  </indi>
  <indi id="I8">
    <name>
      <firstname>Laurence</firstname>
      <lastname>Church</lastname>
    </name>
    <sex type="F" />
    <fams ref="F4" />
  </indi>
  <indi id="I13">
    <name>
      <firstname>Martine</firstname>
      <lastname>B?chi</lastname>
    </name>
    <sex type="F" />
    <famc ref="F3" />
  </indi>
  <indi id="I14">
    <name>
      <firstname>Fran?oise</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="F" />
    <famc ref="F4" />
  </indi>
  <indi id="I6">
    <name>
      <firstname>Nicolas</firstname>
      <lastname>B?chi</lastname>
    </name>
    <sex type="M" />
    <fams ref="F3" />
  </indi>
  <indi id="I1">
    <name>
      <firstname>J?r?me</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <fams ref="F1" />
  </indi>
  <indi id="I7">
    <name>
      <firstname>Arnaud</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <fams ref="F4" />
    <famc ref="F2" />
  </indi>
  <indi id="I2">
    <name>
      <firstname>Estelle</firstname>
      <lastname>Knuth</lastname>
    </name>
    <sex type="F" />
    <fams ref="F1" />
  </indi>
  <indi id="I3">
    <name>
      <firstname>Frederic</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <fams ref="F2" />
    <famc ref="F1" />
  </indi>
  <indi id="I5">
    <name>
      <firstname>Caroline</firstname>
      <lastname>Rabin</lastname>
    </name>
    <sex type="F" />
    <fams ref="F2" />
  </indi>
  <indi id="I11">
    <name>
      <firstname>Dylan</firstname>
      <lastname>B?chi</lastname>
    </name>
    <sex type="M" />
    <famc ref="F3" />
  </indi>
  <indi id="I4">
    <name>
      <firstname>Julie</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="F" />
    <fams ref="F3" />
    <famc ref="F1" />
  </indi>
  <indi id="I17">
    <name>
      <firstname>Sylvain</firstname>
      <lastname>B?chi</lastname>
    </name>
    <sex type="M" />
    <famc ref="F3" />
  </indi>
  <indi id="I16">
    <name>
      <firstname>Alan</firstname>
      <lastname>Turing</lastname>
    </name>
    <sex type="M" />
    <famc ref="F5" />
    <obje>
      <file>http://fr.wikipedia.org/wiki/Alan_Turing</file>
      <form>html</form>
      <titl>Page wikipedia</titl>
    </obje>
  </indi>
  <fam id="F5">
    <husb ref="I9" />
    <wife ref="I10" />
    <chil ref="I16" />
  </fam>
  <fam id="F4">
    <husb ref="I7" />
    <wife ref="I8" />
    <chil ref="I14" />
    <chil ref="I15" />
  </fam>
  <fam id="F1">
    <husb ref="I1" />
    <wife ref="I2" />
    <chil ref="I3" />
    <chil ref="I4" />
    <marr>
      <date>
        <d>7</d>
        <m>AUG</m>
        <y>1987</y>
      </date>
      <plac>United States</plac>
    </marr>
    <obje>
      <file>http://www.liafa.univ-paris-diderot.fr/~carton/gaston-jeanne.gif</file>
      <form>gif</form>
      <titl>TITL</titl>
    </obje>
  </fam>
  <fam id="F3">
    <husb ref="I6" />
    <wife ref="I4" />
    <chil ref="I17" />
    <chil ref="I11" />
    <chil ref="I12" />
    <chil ref="I13" />
    <marr>
      <date>
        <d>13</d>
        <m>JUN</m>
        <y>2001</y>
      </date>
      <plac>Italie</plac>
    </marr>
  </fam>
  <fam id="F2">
    <husb ref="I3" />
    <wife ref="I5" />
    <chil ref="I7" />
    <chil ref="I9" />
    <marr>
      <date>
        <d>7</d>
        <m>APR</m>
        <y>1997</y>
      </date>
      <plac>France</plac>
    </marr>
  </fam>
  <trlr />
</gedcom>

=== kheirus/gedcom_to_xml/xml_generated_files/doe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gedcom SYSTEM "gedcom.dtd">
<gedcom>
  <head>
    <sour>FTW</sour>
    <dest>PAF</dest>
    <date>
      <d>10</d>
      <m>APR</m>
      <y>1999</y>
    </date>
    <file>doe.ged</file>
    <char>ANSI</char>
  </head>
  <indi id="I01">
    <name>
      <firstname>John</firstname>
      <lastname>Doe</lastname>
    </name>
    <sex type="M" />
    <fams ref="F1" />
    <birt>
      <date>
        <d>23</d>
        <m>JAN</m>
        <y>1961</y>
      </date>
      <plac>Australia</plac>
    </birt>
    <deat>
      <date>
        <d>8</d>
        <m>JUL</m>
        <y>1988</y>
      </date>
      <plac>Scotland</plac>
    </deat>
  </indi>
  <indi id="I02">
    <name>
      <firstname>Rosanna</firstname>
      <lastname>Housewife</lastname>
    </name>
    <sex type="F" />
    <fams ref="F1" />
    <birt>
      <date>
        <d>15</d>
        <m>DEC</m>
        <y>1968</y>
      </date>
      <plac>Canada</plac>
    </birt>
    <deat>
      <date>
        <d>8</d>
        <m>JUL</m>
        <y>1988</y>
      </date>
      <plac>Scotland</plac>
    </deat>
  </indi>
  <indi id="I03">
    <name>
      <firstname>Joe</firstname>
      <lastname>Doe</lastname>
    </name>
    <sex type="M" />
    <famc ref="F1" />
    <birt>
      <date>
        <d>15</d>
        <m>JUN</m>
        <y>1988</y>
      </date>
      <plac>United States</plac>
    </birt>
    <deat>
      <date>
        <d>8</d>
        <m>JUL</m>
        <y>1988</y>
      </date>
      <plac>Scotland</plac>
    </deat>
  </indi>
  <fam id="F1">
    <husb ref="I01" />
    <wife ref="I02" />
    <chil ref="I03" />
    <marr>
      <date>
        <d>7</d>
        <m>AUG</m>
        <y>1987</y>
      </date>
      <plac>United States</plac>
    </marr>
  </fam>
  <trlr />
</gedcom>
